### ISSUE TITLE
[Guild] Can't invite player if he is already invited in other guild

### ISSUE THREAD

**Issue by Tibianus** [pandaac-laravel4/bamboo#4]
If the player is already invited to guild, then he can't be invited anymore to another guild

**Comment by eklundchristopher** [comment]
I can't seem to reproduce this issue. I can invite the same player to multiple guilds, can you please provide more information? What distrobution package do you use? What are the exact steps that you go through?

**Comment by eklundchristopher** [comment]
This issue was moved to pandaac/pandaac#1
